FROM maven:3-eclipse-temurin-19-alpine AS builder
RUN apk add git &&\
    git clone https://github.com/ReverseEngineeringDE/SAIC-API-Documentation.git &&\
    cd SAIC-API-Documentation/saic-java-api-gateway/ &&\
    mvn clean install 

FROM eclipse-temurin:19-jre-alpine
COPY --from=builder /SAIC-API-Documentation/saic-java-api-gateway/ismart-api-1.0-SNAPSHOT-full.jar /ismart-api-1.0-SNAPSHOT-full.jar
EXPOSE 42042
CMD ["java","-jar","/ismart-api-1.0-SNAPSHOT-full.jar"] 


